# vim: ft=yaml.ansible
---
- hosts: localhost
  connection: local
  vars:
    user_name: test1
    # u
    user_pwd: $6$5EgjF/SnIsEHlUJP$Rib8QMASRU/yaXj15DtfQXP9s0htgy4BmB/MaqUGvArFNHgv6sHquGpfVapZZxnAMmVXCKrY571fbLhEHfe2W.

  tasks:
    - name: "Full system upgrade"
      pacman:
        update_cache: yes
        upgrade: yes

    - name: "Install basic apps"
      pacman:
        name:
          - base-devel
          - git
          - sudo
        update_cache: yes

    - name: "Edit sudoers to activate sudo group"
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo\s+ALL=(ALL)\s+ALL'
        line: '%sudo ALL=(ALL) ALL'
        validate: '/usr/sbin/visudo -cf %s'

    - name: "Create groups" 
      group: 
        name: "{{ item }}"
        state: present
      loop:
        - "{{ user_name }}"
        - wheel
        - sudo

    - name: "Create user {{ user_name }}"
      user: 
        name: "{{ user_name }}"
        password: "{{ user_pwd }}"
        group: "{{ user_name }}"
        groups:
          - "{{ user_name }}"
          - wheel
          - sudo

