# vim: ft=yaml.ansible
---
- hosts: av1
  connection: local
  become: true

  tasks:
    - name: install packages
      package:
        name: 
          - htop
          - neovim
          - vim
          - zsh
          - openssh
          # - manpath
          - the_silver_searcher
          - exa
          - silverag
          - yarn
          - xclip
          - reflector
          - rsync
          - sudo
          - tmux
          - tig

