# vim: ft=yaml.ansible
---
- hosts: localhost
  connection: local
  become: true

  tasks:

    - name: Full system upgrade `pacman -Suy`
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Install packages from oficial repository
      pacman:
        name: 
          - exa
          - htop
          - neovim
          - openssh
          - reflector
          - rsync
          - stow
          - sudo
          - the_silver_searcher
          - tig
          - tmux
          - vim
          - xclip
          - yarn
          - zsh
          # - manpath

    - name: Clone git repo with dot files
      git:
        repo: https://github.com/undg/.dot
        dest: /home/undg/.dot force=true
        clone: yes
        update: yes

    - name: 
      shell: nvim +PlugInstall +qall --headless
      become_user: undg

    - name: Post install Plug and CoC
      shell: nvim +PlugInstall +qall --headless
      become_user: undg

