# vim: ft=yaml.ansible
# @TODO
# [ ] user agnostic
# [ ] OS agnostic
# [ ] import playbooks conditionally
---
- hosts: localhost
  connection: local

  tasks:
    - name: Full system upgrade `pacman -Suy`
      become: true
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Install packages from official repository
      become: true
          # should be pre installed
      pacman:
        name:

          # should be pre installed
          - base-devel
          - git
          - sudo
          - zsh

          # can be post install
          - exa # ls alternative
          - fd # find alternative
          - htop # top alternative
          - polkit # privilage escalation
          - lxsession # GUI for polkit privilage escalation
          - man-db
          - neovim
          - openssh
          - reflector # pacman source list generator
          - ripgrep # grep alternative
          - rsync
          - stow # dot files symlink helper
          - the_silver_searcher # grep alternative
          - tig # git tree viewer
          - tmux
          - vim
          - xclip
          - yarn
          - npm

    - name: Clone YAY
      when: ansible_facts['distribution'] == 'Archlinux'
      git:
        repo:  https://aur.archlinux.org/yay-bin.git
        dest: /tmp/yay-bin/
        version: master
        clone: yes
        force: yes
        update: yes

    - name: Install YAY
      when: ansible_facts['distribution'] == 'Archlinux'
      shell:
        chdir: /tmp/yay-bin/
        cmd: |
          makepkg -si --noconfirm
          yay -Y --gendb --noconfirm
          yay -Syu --devel --noconfirm
          yay -Y --devel --save --noconfirm


    # @TODO
    # - name: install AUR's packages

    - name: Clone git repo with dot files
      git:
        repo: https://github.com/undg/.dot
        dest: ~/.dot
        version: master
        clone: yes
        update: yes
        force: yes

    - name: Install dot files with stow
      command:
        chdir: ~/.dot/
        cmd: ./install
      register: myoutput
      changed_when: myoutput.rc != 0

    - name: 'Nvim: Post install Plug and CoC'
      command:
        cmd: nvim +PlugInstall +qall --headless
      register: myoutput
      changed_when: myoutput.rc != 0

    # @TODO install nvim dependencies from :checkhealt

