# vim: ft=yaml.ansible
---
- hosts: all
  # connection: local
  # become: true

  tasks:

    - name: Full system upgrade `pacman -Suy`
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Install packages from oficial repository
      pacman:
        name: 
          - htop
          - neovim
          - vim
          - zsh
          - openssh
          # - manpath
          - the_silver_searcher
          - exa
          - yarn
          - xclip
          - reflector
          - rsync
          - sudo
          - tmux
          - tig

    - name: Clone git repo with dot files
      git: 
        repo: https://github.com/undg/.dot force=yes clone=yes
        dest: /home/undg/.dot recursive=yes track_submodules=yes
        clone: yes
      become_user: undg

    - name: Post install Plug and CoC
      shell: nvim +PlugInstall +qall --headless
      become_user: undg

