# vim: ft=yaml.ansible
---
- hosts: localhost
  connection: local

  tasks:

    - name: Full system upgrade `pacman -Suy`
      pacman:
        update_cache: yes
        upgrade: yes
      become: true

    - name: Install packages from oficial repository
      pacman:
        name: 
          - exa
          - htop
          - neovim
          - openssh
          - reflector
          - rsync
          - stow
          - sudo
          - the_silver_searcher
          - tig
          - tmux
          - vim
          - xclip
          - yarn
          - zsh
          - man-db
      become: true

    # @TODO
    # install YAY
    
    # @TODO
    # install AUR's
    
    - name: Clone git repo with dot files
      git:
        repo: https://github.com/undg/.dot
        dest: /home/undg/.dot
        clone: yes
        update: yes
        force: yes

    # @TODO
    # - name: install dot files with stow
    #   shell: /home/undg/.dot/./install

    - name: Post install Plug and CoC
      shell: nvim +PlugInstall +qall --headless

