# vim: ft=yaml.ansible
---
- hosts: localhost
  connection: local
  become: true

  tasks:

    - name: Full system upgrade `pacman -Suy`
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Install packages from oficial repository
      pacman:
        name: 
          - htop
          - neovim
          - vim
          - zsh
          - openssh
          # - manpath
          - the_silver_searcher
          - exa
          - yarn
          - xclip
          - reflector
          - rsync
          - sudo
          - tmux
          - tig

    - name: Post install Plug and CoC
      shell: nvim -c 'PlugInstall|quit|quit'
      args: 
        warn: no

