# vim: ft=yaml.ansible
---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: full sustem upgrade
      pacman:
        update_cache: yes
        upgrade: yes
        name: 
          - htop
          - neovim
          - vim
          - zsh
          - openssh
          # - manpath
          - the_silver_searcher
          - exa
          - yarn
          - xclip
          - reflector
          - rsync
          - sudo
          - tmux
          - tig

