# vim: ft=yaml.ansible
# @TODO
# [ ] user agnostic
# [ ] OS agnostic
# [ ] import playbooks conditionally
---
- hosts: localhost
  connection: local

  tasks:
    - name: Full system upgrade `pacman -Suy`
      become: true
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Install packages from oficial repository
      become: true
      pacman:
        name: 
          - base-devel
          - exa
          - git
          - htop
          - man-db
          - neovim
          - openssh
          - reflector
          - rsync
          - stow
          - sudo
          - the_silver_searcher
          - tig
          - tmux
          - vim
          - xclip
          - yarn
          - zsh

    - name: Clone YAY
      when: ansible_facts['distribution'] == 'Archlinux'
      git:
        repo:  https://aur.archlinux.org/yay-bin.git
        dest: /tmp/yay-bin/
        version: master
        clone: yes
        force: yes
        update: yes

    - name: Install YAY
      when: ansible_facts['distribution'] == 'Archlinux'
      shell: 
        chdir: /tmp/yay-bin/
        cmd: |
          makepkg -si 
          yay -Y --gendb
          yay -Syu --devel
          yay -Y --devel --save

    
    # @TODO
    # - name: install AUR's packages
    
    - name: Clone git repo with dot files
      git:
        repo: https://github.com/undg/.dot
        dest: /home/undg/.dot
        version: master
        clone: yes
        update: yes
        force: yes

    - name: Install dot files with stow
      # chdir: /home/undg/.dot/
      shell:
        chdir: /home/undg/.dot/
        cmd: ./install

    - name: Post install Plug and CoC
      shell:
        cmd: nvim +PlugInstall +qall --headless

