# vim: ft=yaml.ansible
---
- hosts: localhost
  connection: local

  tasks:
    - name: Full system upgrade `pacman -Suy`
      pacman:
        update_cache: yes
        upgrade: yes
      become: true

    - name: Install packages from oficial repository
      pacman:
        name: 
          - base-devel
          - exa
          - git
          - htop
          - man-db
          - neovim
          - openssh
          - reflector
          - rsync
          - stow
          - sudo
          - the_silver_searcher
          - tig
          - tmux
          - vim
          - xclip
          - yarn
          - zsh
      become: true

    - name: Clone YAY
      git:
        repo:  https://aur.archlinux.org/yay-bin.git
        dest: /tmp/yay-bin/
        version: master
        clone: yes
        force: yes
        update: yes

    - name: Install YAY
      command: 
        chdir: /tmp/yay-bin/
        cmd: makepkg -si 
      # become: true
    
    # @TODO
    # - name: install AUR's packages
    
    - name: Clone git repo with dot files
      git:
        repo: https://github.com/undg/.dot
        dest: /home/undg/.dot
        version: master
        clone: yes
        update: yes
        force: yes

    # @TODO
    - name: Install dot files with stow
      script: /home/undg/.dot/./install

    - name: Post install Plug and CoC
      script: nvim +PlugInstall +qall --headless

